layout: sidebar
style: dark

plugins:
    - jekyll-octicons
    - jekyll-github-metadata
    - jemoji

permalink: /:year/:month/:day/:title/

defaults:
    - scope:
          path: '' # an empty string here means all files in the project
          type: 'posts'
      values:
          layout: 'post'

projects:
    sort_by: pushed
    # sort_by options:
    #   - pushed
    #   - stars
    limit: 9
    exclude:
        archived: false
        forks: true
        projects:
        # - repo-name

social_media:
    # behance: your_username
    # dribbble: your_username
    facebook: stefano.lepera
    # hackerrank: your_username
    # instagram: your_username
    # keybase: your_username
    linkedin: stefanolepera
    # mastodon: your_username
    # medium: your_username
    # stackoverflow: your_user_id
    # telegram: your_username
    twitter: stefanolepera
    # unsplash: your_username
    # vk: your_username
    # website: http://your_website_url
    # youtube: your_username

topics:
    - name: React
      web_url: https://github.com/topics/react
      image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/react/react.png

    - name: Redux
      web_url: https://github.com/topics/redux
      image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/redux/redux.png

    - name: RxJS
      web_url: https://github.com/topics/rx-js
      image_url: https://avatars3.githubusercontent.com/u/6407041?s=200&v=4
